nginx:
  build: images/nginx
  command: nginx -g "daemon off;"
  links:
    - php
  ports:
    - "80:80"
php:
  build: .
  volumes:
    - ./:/var/www/html
  working_dir: /var/www/html
  command: php-fpm
  links:
    - db:mongo
  ports:
    - "9000:9000"
  env_file:
    - .env
db:
  image: mongo
  environment:
    MONGO_DATA_DIR: /data/db